/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hrms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RONIESE MAMAED
 */
public class ProcessSalary extends javax.swing.JFrame {

    /**
     * Creates new form ProcessSalary
     */
    public ProcessSalary() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SearchID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        EmployeeID = new javax.swing.JTextField();
        Department = new javax.swing.JTextField();
        EmployeeName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BaseSalary = new javax.swing.JTextField();
        Overtime = new javax.swing.JTextField();
        Incentives = new javax.swing.JTextField();
        Bonus = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Deduct = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Tax = new javax.swing.JTextField();
        Loan = new javax.swing.JTextField();
        Late = new javax.swing.JTextField();
        Absent = new javax.swing.JTextField();
        Earn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        Calculate = new javax.swing.JButton();
        Calculate1 = new javax.swing.JButton();
        Calculate2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Print = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Process Salary");

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hrms/527041411_2020830325117528_5934316394890357605_n.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Process Employee Salary");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(216, 216, 216)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        SearchID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIDActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Search SalaryID");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Employee Name");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Employee ID");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Department");

        BaseSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaseSalaryActionPerformed(evt);
            }
        });

        Overtime.setText("0");
        Overtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OvertimeActionPerformed(evt);
            }
        });

        Incentives.setText("0");
        Incentives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncentivesActionPerformed(evt);
            }
        });

        Bonus.setText("0");
        Bonus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BonusActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EARNINGS/INCOME");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Base Salary");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Overtime");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Incentives");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bonus");

        Deduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeductActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TOTAL EARNINGS");

        Tax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaxActionPerformed(evt);
            }
        });

        Loan.setText("0");
        Loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanActionPerformed(evt);
            }
        });

        Late.setText("0");
        Late.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LateActionPerformed(evt);
            }
        });

        Absent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsentActionPerformed(evt);
            }
        });

        Earn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EarnActionPerformed(evt);
            }
        });

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("DEDUCTIONS");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TAX");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("LOAN");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("LATE/EARLY OUT");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ABSENT");

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("NET PAY");

        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("TOTAL DEDUCTION");

        Calculate.setText("Total");
        Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateActionPerformed(evt);
            }
        });

        Calculate1.setText("Total");
        Calculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate1ActionPerformed(evt);
            }
        });

        Calculate2.setText("Total");
        Calculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15%", "20%", "25%" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Print.setText("Print Salary");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });

        Back.setText("Go Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BaseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Incentives, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(138, 138, 138)
                                .addComponent(jLabel21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(295, 295, 295)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Calculate)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Earn, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Print, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calculate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Loan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Late, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Absent, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Deduct, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calculate2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Tax)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))))
                .addGap(177, 177, 177))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(Search)
                            .addGap(157, 157, 157)
                            .addComponent(jLabel8)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(149, 149, 149))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(SearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(98, 98, 98)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(387, 387, 387))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(527, 527, 527)
                    .addComponent(jLabel6)
                    .addContainerGap(674, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaseSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(Tax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Overtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21)
                    .addComponent(Loan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Late, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Incentives, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Absent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Earn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(Deduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculate2)
                    .addComponent(Calculate1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calculate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Print)
                .addGap(0, 99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(580, 580, 580)
                    .addComponent(jLabel6)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchIDActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String SalaryID;
        int notFound = 0;
        
          try {
              Class.forName("com.mysql.cj.jdbc.Driver");
              
              String url = "jdbc:MySQL://localhost:3308/hrms";
              String user = "root";
              String pass = "";
              
              Connection con = DriverManager.getConnection(url,user,pass);
              Statement st = con.createStatement();
              
              SalaryID = SearchID.getText();
              if("".equals(SalaryID)){
                  JOptionPane.showMessageDialog(new JFrame(), "ID is required","Dialog", JOptionPane.ERROR_MESSAGE);
              }
              else {
                   String sql = "SELECT p.BaseSalary, p.EmployeeID, e.EmployeeName, e.Department " +
                 "FROM payroll p " +
                 "INNER JOIN employeeinfo e ON p.EmployeeID = e.EmployeeID " +
                 "WHERE p.SalaryID = " + SalaryID;

                  ResultSet rs = st.executeQuery(sql);
    

                  while (rs.next()) {
                   EmployeeID.setText(rs.getString("EmployeeID"));
                   BaseSalary.setText(rs.getString("BaseSalary"));
                   EmployeeName.setText(rs.getString("EmployeeName"));
                   Department.setText(rs.getString("Department"));
     
                   
                   
                   
                   notFound = 1;
                   con.close();
                  }
                  if (notFound == 0){
                      JOptionPane.showMessageDialog(new JFrame(), "Invalid ID","Dialog", JOptionPane.ERROR_MESSAGE);
                  }
              }
              
              } catch (Exception e){
              System.out.println("Error" + e.getMessage());
              }
    }//GEN-LAST:event_SearchActionPerformed

    private void BaseSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaseSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaseSalaryActionPerformed

    private void OvertimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OvertimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OvertimeActionPerformed

    private void IncentivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncentivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncentivesActionPerformed

    private void BonusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BonusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BonusActionPerformed

    private void DeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeductActionPerformed

    private void TaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaxActionPerformed

    private void LoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoanActionPerformed

    private void LateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LateActionPerformed

    private void AbsentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsentActionPerformed

    private void EarnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EarnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EarnActionPerformed

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    private void CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateActionPerformed
        // TODO add your handling code here:
        int totale;
        double totald, total;
         totale= Integer.parseInt(Earn.getText().trim().replace(",",""));
          totald= Double.parseDouble(Deduct.getText().trim().replace(",",""));
          
          total = totale - totald;
          
           Total.setText(String.format("%.2f",total));
        
        
    }//GEN-LAST:event_CalculateActionPerformed


    private void Calculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate1ActionPerformed
        // TODO add your handling code here:
         int bs,ot,in,bn,totale;
  
      
       try{ 
              if("".equals(BaseSalary.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Base Salary is required","Dialog", JOptionPane.ERROR_MESSAGE);
              }
              else if("".equals(Overtime.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Overtime is required/Put 0 if none","Dialog", JOptionPane.ERROR_MESSAGE);
              }
              
              else if("".equals(Incentives.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Incentives is required/Put 0 if none","Dialog", JOptionPane.ERROR_MESSAGE);
              }
               else if("".equals(Bonus.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Bonus is required/Put 0 if none","Dialog", JOptionPane.ERROR_MESSAGE);
              }
             else {
                  bs = Integer.parseInt(BaseSalary.getText().trim().replace(",",""));
                  ot = Integer.parseInt(Overtime.getText().trim().replace(",",""));
                  in = Integer.parseInt(Incentives.getText().trim().replace(",",""));
                  bn = Integer.parseInt(Bonus.getText().trim().replace(",",""));
                  
                  totale=bs+ot+in+bn;
                  
                  Earn.setText(String.valueOf(totale));
                  
               }
            }catch (Exception e){
              System.out.println("Error" + e.getMessage());
          }
    }//GEN-LAST:event_Calculate1ActionPerformed

    private void Calculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate2ActionPerformed
        // TODO add your handling code here:
        int lon,lat,abs,totale;
        double totald=0.0;
        String tax;
  
      
       try{ 
              if("".equals(Tax.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Tax is required","Dialog", JOptionPane.ERROR_MESSAGE);
              }
              else if("".equals(Loan.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Loan is required/Put 0 if none","Dialog", JOptionPane.ERROR_MESSAGE);
              }
              
              else if("".equals(Late.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Late Deductions is required/Put 0 if none","Dialog", JOptionPane.ERROR_MESSAGE);
              }
               else if("".equals(Absent.getText())){
              JOptionPane.showMessageDialog(new JFrame(), "Absent Deductions is required/Put 0 if none","Dialog", JOptionPane.ERROR_MESSAGE);
              }
             else {
                  tax = Tax.getText();
                  lon = Integer.parseInt(Loan.getText().trim().replace(",",""));
                  lat = Integer.parseInt(Late.getText().trim().replace(",",""));
                  abs= Integer.parseInt(Absent.getText().trim().replace(",",""));
                  totale= Integer.parseInt(Earn.getText().trim().replace(",",""));
                  
                  switch (tax){
                      case "15%": 
                          totald= (((totale*12)-250000)* 0.15)/12;break;
                      case "20%": 
                          totald = ((((totale*12)-400000)* 0.20)+22500)/12;break;
                      case "25%": 
                          totald = ((((totale*12)-800000)* 0.25)+102500)/12;break;
                  }
                  
                  totald+= lon + lat + abs;
                  
                  Deduct.setText(String.format("%.2f",totald));
                  
               }
            }catch (Exception e){
              System.out.println("Error" + e.getMessage());
          }
    }//GEN-LAST:event_Calculate2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         String selected = jComboBox1.getSelectedItem().toString();
          Tax.setText(selected);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
        try {
    // File path for saving the PDF
     String empID = EmployeeID.getText();
     String timestamp = new java.text.SimpleDateFormat("yyyy-MM-dd_HH-mm").format(new java.util.Date());
     String filePath = System.getProperty("user.home") + "/Downloads/HRMS_Salary_Report_ID#"+empID+"_"+ timestamp + ".pdf";

    // Create a new PDF document
    com.itextpdf.text.Document document = new com.itextpdf.text.Document();
    com.itextpdf.text.pdf.PdfWriter.getInstance(document, new java.io.FileOutputStream(filePath));
    document.open();

    // Fonts
    com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 16, com.itextpdf.text.Font.BOLD);
    com.itextpdf.text.Font sectionFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 13, com.itextpdf.text.Font.BOLD);
    com.itextpdf.text.Font normalFont = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 12);

    // Title
    com.itextpdf.text.Paragraph title = new com.itextpdf.text.Paragraph("RAM-eSolutions\nEMPLOYEE SALARY REPORT", titleFont);
    title.setAlignment(com.itextpdf.text.Element.ALIGN_CENTER);
    document.add(title);
    document.add(new com.itextpdf.text.Paragraph("Generated on: " + new java.util.Date().toString(), normalFont));
    document.add(new com.itextpdf.text.Paragraph(" ")); // space

    // Employee Info Section
    document.add(new com.itextpdf.text.Paragraph("Employee Information", sectionFont));
    document.add(new com.itextpdf.text.Paragraph("Employee ID: " + EmployeeID.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Employee Name: " + EmployeeName.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Department: " + Department.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph(" "));

    // Salary Info Section
    document.add(new com.itextpdf.text.Paragraph("Salary Information", sectionFont));
    document.add(new com.itextpdf.text.Paragraph(" "));
    document.add(new com.itextpdf.text.Paragraph("Earnings: ", sectionFont));
    document.add(new com.itextpdf.text.Paragraph("Base Salary: " + BaseSalary.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Overtime: " + Overtime.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Incentives: " + Incentives.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Bonus: " + Bonus.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Total Earnings: " + Earn.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph(" "));
    document.add(new com.itextpdf.text.Paragraph("Deductions: ", sectionFont));
    document.add(new com.itextpdf.text.Paragraph("Tax: " + Tax.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Loan: " + Loan.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Late Deduction: " + Late.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Absent Deduction: " + Absent.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph("Total Deduction: " + Deduct.getText(), normalFont));
    document.add(new com.itextpdf.text.Paragraph(" "));
    document.add(new com.itextpdf.text.Paragraph("Total Salary: " + Total.getText(), sectionFont));

    // Close PDF
    document.close();

    javax.swing.JOptionPane.showMessageDialog(this,
        "Employee report exported successfully!\nSaved at: " + filePath,
        "Export Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "Error exporting PDF: " + e.getMessage(),
        "Export Failed", javax.swing.JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_PrintActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Salary_Info pay = new Salary_Info();
                     pay.setVisible(true);
                     pay.pack();
                     this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProcessSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProcessSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProcessSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProcessSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProcessSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absent;
    private javax.swing.JButton Back;
    private javax.swing.JTextField BaseSalary;
    private javax.swing.JTextField Bonus;
    private javax.swing.JButton Calculate;
    private javax.swing.JButton Calculate1;
    private javax.swing.JButton Calculate2;
    private javax.swing.JTextField Deduct;
    private javax.swing.JTextField Department;
    private javax.swing.JTextField Earn;
    private javax.swing.JTextField EmployeeID;
    private javax.swing.JTextField EmployeeName;
    private javax.swing.JTextField Incentives;
    private javax.swing.JTextField Late;
    private javax.swing.JTextField Loan;
    private javax.swing.JTextField Overtime;
    private javax.swing.JButton Print;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchID;
    private javax.swing.JTextField Tax;
    private javax.swing.JTextField Total;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
